CREATE TABLE notes (
note_id BIGINT NOT NULL AUTO_INCREMENT,
username VARCHAR(50) NULL DEFAULT NULL,
currency_id BIGINT NULL DEFAULT NULL,
currency_price_usd DOUBLE(40,2) NULL DEFAULT NULL,
date_note DATETIME NULL DEFAULT NULL,
PRIMARY KEY (note_id)
);